"Duplicate 'Balanced' Power Scheme..."
"GUID: FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF"
"Name: AHK"

POWERCFG /DUPLICATESCHEME 381b4222-f694-41f0-9685-ff5bb260df2e FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF
POWERCFG /CHANGENAME FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF "AHK" "Balanced power plan for AHK: CPU_Freq_Cores_Manager"
Pause
